# check config: flexget check
# execute (cron): flexget --cron execute
# execute one task:
#   flexget execute --task get-subtitles
#   flexget execute --task search-series --discover-now
# execute one task (test): flexget --text execute --task get-subtitles
# get series list: flexget series list
# show info: flexget series show NAME
# download again:
#   flexget series forget NAME
#   flexget series begin NAME S03E17
# failed: flexget failed list || flexget failed clear

# https://flexget.com/Plugins/variables
variables: variables.yml

# scheduling
# https://flexget.com/InstallWizard/Linux/Scheduling
# https://flexget.com/InstallWizard/Linux/AutoStart:w
#
# To start the daemon at system boot you could use one of the following cronjob:
#   @reboot /usr/local/bin/flexget daemon start -d
#   @reboot . $HOME/.virtualenvs/flexget/bin/activate && flexget daemon start -d --autoreload-config
# To manage daemon:
#   flexget daemon stop
#   flexget daemon status
#   flexget daemon reload-config

# https://flexget.com/Plugins/Daemon/scheduler
schedules:
  - tasks: '*'
    interval:
      hours: 3
  # - tasks: [search-series, get-subtitles]
  #   interval:
  #     minutes: 30 # weeks|days|hours|minutes
  #     jitter: 60
  # - tasks: '*'
  #     schedule:
  #       minute: "*/15"
  #       hour: 8-18/2
  #       day: 1,2
  #       day_of_week: tue,thu
  #       week: X
  #       month: X
  #       year: X

templates:
  tv:

    # manipulate:
    #   - title: &the
    #       replace:
    #         regexp: '^The\W'
    #         format: ''
    #   - filename: *the
    #   - series_name: *the
    plugin_priority:
      # manipulate must fix the titles before metainfo_series
      manipulate: 255

    # http://flexget.com/wiki/Plugins/content_filter
    content_filter:
      require_mainfile: yes
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
      reject:
        - '*.lnk'
        - '*.wmv'
        - '*.rar'
        - '*.zip'
        - '*password*'

    # https://flexget.com/Plugins/content_size
    content_size:
      min: 300
      max: 2000

    # http://flexget.com/wiki/Plugins/thetvdb_lookup
    thetvdb_lookup: yes

    # https://flexget.com/Plugins/headers
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"

    # https://flexget.com/Plugins/imdb_lookup
    # imdb_lookup: yes

    # https://flexget.com/Plugins/require_field
    # require_field:
    #   - tvdb_first_air_date

    # https://flexget.com/Plugins/if
    if:
      - tvdb_first_air_date != None and tvdb_first_air_date > now: reject

    # http://flexget.com/wiki/Plugins/manipulate
    manipulate:
      - url:
          replace:
            regexp: '&amp'
            format: '&'
      - description:
          remove: yes

    # http://flexget.com/wiki/Plugins/private_torrents
    private_torrents: no

    # http://flexget.com/wiki/Plugins/torrent_alive
    torrent_alive:
      min_seeds: 7
      reject_for: 1 day

    # https://flexget.com/Plugins/reorder_quality
    # reorder_quality:
    #   webdl:
    #     above: dvdrip

    # http://flexget.com/wiki/Plugins/regexp
    regexp:
      reject:
        #- WEB
        - WEB-DL
        - FRENCH
        - VOSTFR

    # http://flexget.com/wiki/Plugins/series
    # http://flexget.com/wiki/Cookbook/Series
    series:
      settings:
        tv:
          exact: yes
          propers: 3 days
          # https://flexget.com/Qualities#Requirements
          quality: hdtv-dvdrip 1080p
          set:
            path: '{? series.settings.tv.set.path ?}'
            # path: /mnt/data/Series/{{series_name}}
            main_file_only: yes
            # If the main file is NOT found it will exclude any file matching
            # the patterns listed in exclude_files.
            # If a main file IS found any *.txt file will be downloaded.
            # Because include_subs is set any *.srt, *.sub, *.idx, *.ass, *.ssa
            # will also be downloaded.
            skip_files:
              - '*.jpg'
              - '*.nfo'
              - '*.sfv'
              - '*.txt'
              - '*[sS]ample*'
            include_files:
              - '*.txt'
            thetvdb_lookup: yes
            include_subs: yes
      tv:
        # http://flexget.com/wiki/Plugins/series/identified_by
        # identified_by: auto
        # ep_regexp: (\d\d\d)
        # name_regexp: ^Name.* Season \d
        - Stan Lees Lucky Man:
            begin: S02E01
        - The Sinner:
            # alternate_name: The Sinner (2017)
            begin: S03E01
        - The Walking Dead:
            begin: S10E09

    # http://flexget.com/wiki/Plugins/transmission
    # pip install transmissionrpc
    transmission:
      netrc: '{? transmission.netrc ?}'

    # https://flexget.com/Plugins/domain_delay
    domain_delay:
      rarbg.com: 3 seconds

    notify:
      entries:
        # https://flexget.com/Entry#Knownfields
        message: 'Downloading: {{series_name}} {{series_id}} ⭐{{tvdb_rating}} ⏲️{{tvdb_runtime}}min'
        via:
          # https://flexget.com/Plugins/Notifiers/telegram
          # pip install python-telegram-bot
          - telegram:
              bot_token: '{? telegram.bot_token ?}'
              parse_mode: markdown
              disable_previews: no
              recipients:
                - username: '{? telegram.username ?}'
          # https://flexget.com/Plugins/Notifiers/xmpp
          # pip install sleekxmpp dnspython
          # - xmpp:
          #     sender: '{? xmpp.sender ?}'
          #     password: '{? xmpp.password ?}'
          #     recipients: '{? xmpp.recipients?}'
          #     # title: 'New episode(s)!'
          #     # text: '{{series_name}} {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %}: {{tvdb_ep_name}}{% endif %}'

    # http://flexget.com/wiki/Plugins/headers
    # http://discuss.flexget.com/t/torcache-client-error-403-forbidden/1469/6
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 5.1; rv:16.0) Gecko/20100101 Firefox/16.0"

# http://flexget.com/wiki/Plugins/email
# email:
#   from: '{? email.from ?}'
#   to: '{? email.to ?}'

tasks:

  eztv.ag:
    # https://flexget.com/Plugins/rss
    rss: https://eztv.ag/ezrss.xml
    template: tv
    # content_size:
    #   min: 250
    #   max: 400
    #     manipulate:
    #      - title:
    #          replace:
    #            regexp: '\['
    #            format: '.'
    #   strict: no

  # new shiny automatic searching
  # warning: use OpenDNS: 208.67.222.222 and 208.67.220.220
  search-series:
    template: tv
    verify_ssl_certificates: no
    # http://flexget.com/wiki/Plugins/discover
    discover:
      release_estimations:
        optimistic: 7 days
      what:
        - next_series_episodes: yes
      # https://flexget.com/Searches
      # flexget plugins --interface search
      # flexget doc yts
      from:
        - 1337x: yes
        - descargas2020: yes
        - limetorrents:
            category: tv
            order_by: date
        - rarbg:
            category: [2, 18, 41, 49]
            sorted_by: seeders
            use_tvdb: True
        - yts: yes
        # - argenteam:
        #     force_subtitles: no
        # - newtorrents: yes
        # - piratebay:
        #     category: tv
        #     sort_by: seeds
        # - torrentz: good
      interval: 3 hour  # Search for expected episodes again every hour

  get-subtitles:
    # https://flexget.com/Plugins/filesystem
    filesystem:
      path: '{? series.settings.tv.set.path ?}'
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    seen: local
    # http://flexget.com/wiki/Plugins/subliminal
    subliminal:
      languages:
        - eng
      # alternatives:
      #   - esp
      exact_match: yes
      providers: [opensubtitles, thesubdb, podnapisi, addic7ed, tvsubtitles]
      #single: no

